services:
  # API de prédiction
  api:
    build: .
    container_name: air-quality-api
    ports:
      - "8000:8000"
    volumes:
      - ./mlflow.db:/app/mlflow.db
      - ./models:/app/models
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db
    restart: unless-stopped
